[project]
name = "python-mongoclass"
version = "0.1.20"
description = "mongoclass"
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = [
    "dnspython >= 2.2.1, <3",
    "mongita >= 1.1.1, <2",
    "pymongo >= 4.5.0, <5",
]
[project.optional-dependencies]
dev = [
    "icecream",
    "ipython",
    "ipython-suggestions",
    "restmagic",
    "mypy",
    "pip-tools",
    "pyflyby",
    "twine",
]

tests = [
    "coverage[toml] >=6, <7",
    "tox >=4.6.4, <5",
]

[tool.setuptools.packages.find]
exclude = ["tests"]

[build-system]
requires = ['setuptools', 'setuptools_scm>=6.2', 'wheel']
build-backend = 'setuptools.build_meta'

[tool.coverage.report]
skip_empty = true
[tool.coverage.html]
directory = "coverage_html_report"
[tool.coverage.run]
branch = true
source = ["mongoclass"]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py{310, 311, 312dev}
isolated_build = True
skip_missing_interpreters = true
[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312-dev

[testenv]
passenv = USER
commands = python -m unittest
"""
