[project]
name = "python-mongoclass"
description = "mongoclass"
version = "0.1.1"
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = [
    "dnspython >= 2.2.1, <3",
    "mongita >= 1.1.1, <2"
]
[project.optional-dependencies]
dev = [
    "black",
    "icecream",
    "ipython",
    "ipython-suggestions",
    "restmagic",
    "mypy",
    "pip-tools",
    "pyflyby",
    "python-semantic-release",
    "twine",
    "vendorize"
]
docs = [
    "docutils",
    "sphinx",
    "sphinx-click",
    "sphinx-rtd-theme",
    "sphinxcontrib-napoleon"
]
tests = [
    "coverage[toml] >=6, <7",
    "darglint >=1.8.1, <2",
    "pydocstyle >=6.3, <7",
    "pytest >=7, <8",
    "pytest-asyncio >=0.21.1, <1",
    "pytest-cov >=4, <5",
    "pytest-doctestplus >=0.13, <1",
    "pytest-mock >=3, <4",
    "pytest-xdist >=2, <3",
    "pytest-remotedata >=0.4.0, <1",
    "pytest-lazy-fixture ~=0.6.3",
    "pytest-sugar >=0.9.7, <1",
    "responses==0.21.0",
    "requests-mock >=1.10.0, <2",
    "ruff >=0.0.282, <0.1",
    "tox >=4.6.4, <5",
    "types-pytest-lazy-fixture >=0.6.3.3",
]

[tool.setuptools]
packages = ["mongoclass"]  # ["."] by default

[build-system]
requires = ['setuptools', 'wheel']
build-backend = 'setuptools.build_meta'
